"""Public API for Orus Ontology."""

from orus_ontology.assertions import (
    Assertion,
    AssertionKind,
    AssertionTarget,
    ObjectTarget,
    SourceReference,
    TargetKind,
    TemporalContext,
    ValueTarget,
)
from orus_ontology.errors import (
    BridgeError,
    ErrorCode,
    IdentityError,
    MappingError,
    MaterializationError,
    OntologyError,
    QueryError,
    ReasoningError,
    SchemaError,
    StorageError,
    VersionError,
)
from orus_ontology.identity import IdentityNormalizer, IdentitySpec
from orus_ontology.identity.candidate import MatchCandidate
from orus_ontology.identity.generator import IdentityGenerator
from orus_ontology.identity.resolution import ResolutionDecision, ResolutionOutcome
from orus_ontology.interchange import (
    CONTRACT_VERSION,
    BridgeRun,
    InterchangeEnvelope,
    InterchangeSource,
    RunStatus,
    SubprocessBridge,
    encode_jsonl,
    read_jsonl,
)
from orus_ontology.mapping import (
    MappingCompiler,
    MappingDefinition,
    MappingPlan,
    ObjectMapping,
    PropertyMapping,
    RecordErrorPolicy,
    RelationMapping,
    SourceContract,
    SourceField,
    TransformName,
)
from orus_ontology.materialization import (
    BatchMaterializer,
    CanonicalRecord,
    MaterializedBatch,
    ObjectInstance,
    QuarantinedRecord,
    RelationInstance,
)
from orus_ontology.metamodel import (
    ObjectType,
    OntologyDefinition,
    OntologyStatus,
    PropertyCardinality,
    PropertyConstraints,
    PropertyType,
    RelationCardinality,
    RelationType,
    SchemaValidator,
    ValueType,
)
from orus_ontology.query import (
    CyclePolicy,
    FilterOperator,
    ObjectQuery,
    PropertyFilter,
    QueryService,
    TraversalHop,
    TraversalQuery,
    TraversalResult,
)
from orus_ontology.reasoning import (
    ConditionOperator,
    InferenceExplanation,
    InferenceRule,
    ReasoningEngine,
    ReasoningLimits,
    ReasoningResult,
    RuleConclusion,
    RuleCondition,
)
from orus_ontology.registry import (
    ChangeCompatibility,
    MigrationPlan,
    MigrationStep,
    MigrationStrategy,
    SchemaRegistry,
    VersionChange,
    VersionDiff,
    compare_versions,
)
from orus_ontology.storage import MemoryStore, RelationDirection

__all__ = [
    "CONTRACT_VERSION",
    "Assertion",
    "AssertionKind",
    "AssertionTarget",
    "BatchMaterializer",
    "BridgeError",
    "BridgeRun",
    "CanonicalRecord",
    "ChangeCompatibility",
    "ConditionOperator",
    "CyclePolicy",
    "ErrorCode",
    "FilterOperator",
    "IdentityError",
    "IdentityGenerator",
    "IdentityNormalizer",
    "IdentitySpec",
    "InferenceExplanation",
    "InferenceRule",
    "InterchangeEnvelope",
    "InterchangeSource",
    "MappingCompiler",
    "MappingDefinition",
    "MappingError",
    "MappingPlan",
    "MatchCandidate",
    "MaterializationError",
    "MaterializedBatch",
    "MemoryStore",
    "MigrationPlan",
    "MigrationStep",
    "MigrationStrategy",
    "ObjectInstance",
    "ObjectMapping",
    "ObjectQuery",
    "ObjectTarget",
    "ObjectType",
    "OntologyDefinition",
    "OntologyError",
    "OntologyStatus",
    "PropertyCardinality",
    "PropertyConstraints",
    "PropertyFilter",
    "PropertyMapping",
    "PropertyType",
    "QuarantinedRecord",
    "QueryError",
    "QueryService",
    "ReasoningEngine",
    "ReasoningError",
    "ReasoningLimits",
    "ReasoningResult",
    "RecordErrorPolicy",
    "RelationCardinality",
    "RelationDirection",
    "RelationInstance",
    "RelationMapping",
    "RelationType",
    "ResolutionDecision",
    "ResolutionOutcome",
    "RuleConclusion",
    "RuleCondition",
    "RunStatus",
    "SchemaError",
    "SchemaRegistry",
    "SchemaValidator",
    "SourceContract",
    "SourceField",
    "SourceReference",
    "StorageError",
    "SubprocessBridge",
    "TargetKind",
    "TemporalContext",
    "TransformName",
    "TraversalHop",
    "TraversalQuery",
    "TraversalResult",
    "ValueTarget",
    "ValueType",
    "VersionChange",
    "VersionDiff",
    "VersionError",
    "compare_versions",
    "encode_jsonl",
    "read_jsonl",
]

__version__ = "0.1.0"
